// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBog795SWSW-Jt3F5njo0x38Xv3bU-axeo',
    appId: '1:351644872444:web:4c0bef50ea098199a0f179',
    messagingSenderId: '351644872444',
    projectId: 'lively-option-392317',
    authDomain: 'lively-option-392317.firebaseapp.com',
    storageBucket: 'lively-option-392317.appspot.com',
    measurementId: 'G-FE17ECNDZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgjLGknSvdS76b7VmSPKUh_wMIBRQUV0',
    appId: '1:351644872444:android:135f9a4d2229437ca0f179',
    messagingSenderId: '351644872444',
    projectId: 'lively-option-392317',
    storageBucket: 'lively-option-392317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbUW1giD2VCJsb5OubYmk7y5aePd0NEAk',
    appId: '1:351644872444:ios:062c0cf5d999cc67a0f179',
    messagingSenderId: '351644872444',
    projectId: 'lively-option-392317',
    storageBucket: 'lively-option-392317.appspot.com',
    iosClientId: '351644872444-1b960i38q6c9gu1gdi1i6s8rhkp3btao.apps.googleusercontent.com',
    iosBundleId: 'io.nyuad.laundry.notification',
  );
}
